name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main  # change if using a different default branch

permissions:
  contents: write  # REQUIRED for pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MkDocs and theme
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          mkdocs gh-deploy --force
